nof_p: 1
1:
    name: test
    nof_iterations: 105
    learning_rate: 0.01
    learning_rate_steps: 1000
    learning_rate_decay: 1000
    load_model_name: "model.ckpt"
    use_saved_model: False
    gpu: 0
2:
    name: test2
    nof_iterations: 1005
    learning_rate: 0.01
    learning_rate_steps: 1000
    learning_rate_decay: 0.5
    save_model_name: "model.ckpt"
    load_model_name: "model.ckpt"
    use_saved_model: False
    gpu: 1