nof_p: 1
1:
    name: test14 
    nof_iterations: 10000
    learning_rate: 0.0005
    learning_rate_steps: 1000
    learning_rate_decay: 0.5
    load_model_name: "test14_module.ckpt"
    use_saved_model: True
    gpu: 2
2:
    name: test2
    nof_iterations: 10000
    learning_rate: 0.0001
    learning_rate_steps: 1000
    learning_rate_decay: 0.5
    load_model_name: "model.ckpt"
    use_saved_model: False
    gpu: 1
