nof_p: 1
1:
    name: lh_relu_2
    nof_iterations: 10000
    learning_rate: 0.005
    learning_rate_steps: 10
    learning_rate_decay: 0.5
    load_model_name: "lh_relu_module.ckpt"
    use_saved_model: True
    rnn_steps: 1
    loss_func: "all"
    lr_object_coeff: 1
    gpu: 0
