name: gpi_e2e_faster
nof_iterations: 10000
learning_rate: 0.0001
learning_rate_steps: 1000
learning_rate_decay: 0.5
load_model_name: "gpi_e2e_best_module.ckpt"
use_saved_model: False
batch_size: 1
predicate_pos_neg_ratio: 10
lr_object_coeff: 4
layers: [256, 256]
gpu: 3

